.main clear
vlib work
vlog -f src_files.list +cover -covercells
vsim -voptargs=+acc +UVM_VERBOSITY=UVM_HIGH work.pcie_top +flit_mode -classdebug -uvmcontrol=all -cover 
run 0
add wave -position insertpoint  \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/current_state \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.current_state \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/seq_item_rx \
sim:/uvm_root/uvm_test_top/top_env/u_vip/tx_agent/drv/seq_item_drv \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/cfg.scaled_fc_active \
sim:/uvm_root/uvm_test_top/top_env/u_vip/cfg.local_fc_credits_register \
sim:/uvm_root/uvm_test_top/top_env/u_vip/cfg.remote_fc_credits_register \
sim:/uvm_root/uvm_test_top/top_env/u_vip/tx_agent/drv/seq_item_drv \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/FI1 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.FI1 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/FI2 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.FI2 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/cfg.local_register_feature \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/cfg.remote_register_feature \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/cfg.feature_exchange_cap \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/current_state \
sim:/uvm_root/uvm_test_top/top_env/d_vip/scoreboard/ref_model.current_state \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/seq_item_rx \
sim:/uvm_root/uvm_test_top/top_env/d_vip/tx_agent/drv/seq_item_drv \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/cfg.scaled_fc_active \
sim:/uvm_root/uvm_test_top/top_env/d_vip/cfg.local_fc_credits_register \
sim:/uvm_root/uvm_test_top/top_env/d_vip/cfg.remote_fc_credits_register \
sim:/uvm_root/uvm_test_top/top_env/d_vip/tx_agent/drv/seq_item_drv \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/FI1 \
sim:/uvm_root/uvm_test_top/top_env/d_vip/scoreboard/ref_model.FI1 \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/FI2 \
sim:/uvm_root/uvm_test_top/top_env/d_vip/scoreboard/ref_model.FI2 \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/cfg.local_register_feature \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/cfg.remote_register_feature \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/cfg.feature_exchange_cap  \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.FI1 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.FI2 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_p_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_np_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_cpl_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_p_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_np_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/scoreboard/ref_model.fi1_cpl_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/cfg.flit_mode_enable \
sim:/uvm_root/uvm_test_top/top_env/d_vip/state_machine/cfg.flit_mode_enable \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_p_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_p_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_np_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_np_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_cpl_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init2_cpl_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_p_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_p_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_np_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_np_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_cpl_f_s \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/init1_cpl_f_d \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/FI2 \
sim:/uvm_root/uvm_test_top/top_env/u_vip/state_machine/FI1

run -all